UIPFI-107 - Find an instance - Apply Previous/Next Pagination
folio-org/ui-plugin-find-instance pull request #148
Opened 2022-10-18 05:11 UTC by Terala-Priyanka

## Purpose
Find an instance - Apply Previous/Next Pagination

## Approach
Existing code uses fetchMore method to fetch next chunk of records. Hence, offset is incremented on every call.
Hence, in this implementation, fetchmore is conditionally called.
for example-
- on initial search, 100 records are fetched - record range would be 1-100
- on clicking next button (on pagination row), next 100 records are also fetched, which makes the total records fetched as 200 and the offset used in last GET call is 100, record range would be 101-200
- for instance, now previous button (on pagination row) is clicked, MCLRenderer now renders with record range 1-100 which is picked from already fetched records.
- if next button is clicked, MCLRenderer renders with record range 101 - 200, which are again picked from already fetched records.
- if next button is clicked once again, then next chunk of records is now fetched, which makes the total records fetched as 300 and the offset used in last GET call is 200, record range would be 201-300

## Refs
https://issues.folio.org/browse/UIPFI-107

## Screenshots
![chrome_tb4lIpFMtV](https://user-images.githubusercontent.com/104053200/196338166-535557d6-b645-44cd-8179-06cdd41d3f45.gif)

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2022-10-18 05:27 UTC, Terala-Priyanka commented
@folio-org/fe-tl-reviewers 
Please review

2022-10-18 08:26 UTC, BogdanDenis requested changes

2022-10-18 08:26 UTC, BogdanDenis commented on InstanceSearch/FindInstanceContainer.js
> +        if (this.currentPage * PAGE_SIZE > records.length) {
If you're using `RESULT_COUNT_INCREMENT` in `fetchMore` I think it'll be better to use it instead of `PAGE_SIZE`. This way it'll be just one constant

2022-10-18 08:26 UTC, BogdanDenis commented on InstanceSearch/FindInstanceContainer.js
> +        ...this.state,
`this.setState` under the hood already uses destructuring, so you can just call it like `this.setState({ direction })` and it'll have the same effect

2022-10-18 08:26 UTC, BogdanDenis commented on PluginFindRecord/PluginFindRecordModal.js
> +const PAGE_SIZE = 100;
Maybe pass it as a prop to `PluginFindRecordModal` or place `RESULT_COUNT_INCREMENT` in constants file and import it here?

2022-10-18 08:47 UTC, Terala-Priyanka commented on InstanceSearch/FindInstanceContainer.js
> +        if (this.currentPage * PAGE_SIZE > records.length) {
replaced PAGE_SIZE with RESULT_COUNT_INCREMENT

2022-10-18 08:49 UTC, Terala-Priyanka commented on PluginFindRecord/PluginFindRecordModal.js
> +const PAGE_SIZE = 100;
passed through props

2022-10-18 08:50 UTC, Terala-Priyanka commented on InstanceSearch/FindInstanceContainer.js
> +        ...this.state,
updated setstate

2022-10-18 09:00 UTC, BogdanDenis approved these changes

2022-10-18 13:37 UTC, mkuklis commented on InstanceSearch/FindInstanceContainer.js
> +      this.setState({ direction });
@Terala-Priyanka, is `direction` used anywhere? I tried to find a reference to it but I can't find it.

2022-10-20 05:51 UTC, Terala-Priyanka commented on InstanceSearch/FindInstanceContainer.js
> +      this.setState({ direction });
@mkuklis 
Thank you for the observation. I have refined the code. Please review

2022-10-21 12:39 UTC, mkuklis approved these changes
@Terala-Priyanka nice work!

2022-10-21 13:07 UTC, merged