UIPFI-140: ECS: Properly filter location options in filters, even if there are duplicates.
folio-org/ui-plugin-find-instance pull request #205
Opened 2024-01-29 14:08 UTC by Dmytro-Melnyshyn

## Description
This was an issue where the list options were not displayed correctly after the user entered values into the text box for filters that used locations.

The reason is that there were locations with the same labels, and the label was used as a key in the list of options.

This is because locations are collected from all tenants and may have the same label. In our case, even the same id - probably due to environment setup, but in any case we remove duplicates with the same id - there is no sense in having them.

## Approach

## Refs

## Screenshots

https://github.com/folio-org/ui-plugin-find-instance/assets/77053927/4f65aa70-345a-49eb-b54d-38b30713198b

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [ ] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2024-01-30 10:15 UTC, BogdanDenis requested changes

2024-01-30 10:15 UTC, BogdanDenis commented on Imports/imports/InstanceFilters/InstanceFilters.js
> +  const locationOptions = getLocationFilterOptions(locations, consortiaTenants, stripes);
I think this formatting should happen in `<LocationFilter>` because it's a part of logic of that filter. Parent components should only pass locations and consortiaTenants as props

2024-01-30 14:50 UTC, BogdanDenis approved these changes

2024-01-31 11:50 UTC, zburke approved these changes
The PR description here was really helpful; thank you! Refactoring to `<LocationFilter>` was a great idea for consolidating things; thank you again!

2024-01-31 11:51 UTC, merged